INCLUDES += -I$(DIR_TASK_USER)/EcTaskUserBase
INCLUDES += -I$(DIR_TASK_USER)/EcTaskUserFactory
INCLUDES += -I$(DIR_TASK_USER)/EcUser_1
INCLUDES += -I$(DIR_TASK_USER)/EcUser_2
INCLUDES += -I$(DIR_TASK_USER)/EcUser_3
INCLUDES += -I$(DIR_TASK_USER)/EcUser_4
INCLUDES += -I$(DIR_TASK_USER)/EcUser_5
