SRCS += $(wildcard $(DIR_TASK_ETHERCAT_SLAVE_SERVO)/EcTaskEthercatSlaveServoBase/*.cpp)
SRCS += $(wildcard $(DIR_TASK_ETHERCAT_SLAVE_SERVO)/EcTaskEthercatSlaveServoFactory/*.cpp)
SRCS += $(wildcard $(DIR_TASK_ETHERCAT_SLAVE_SERVO)/EcCia402/*.cpp)
SRCS += $(wildcard $(DIR_TASK_ETHERCAT_SLAVE_SERVO)/EcSlavePitchDrive/*.cpp)
SRCS += $(wildcard $(DIR_TASK_ETHERCAT_SLAVE_SERVO)/EcSlaveDenNetE/*.cpp)
SRCS += $(wildcard $(DIR_TASK_ETHERCAT_SLAVE_SERVO)/EcSlaveDenXcrE/*.cpp)
SRCS += $(wildcard $(DIR_TASK_ETHERCAT_SLAVE_SERVO)/EcSlaveElmoDrive/*.cpp)
SRCS += $(wildcard $(DIR_TASK_ETHERCAT_SLAVE_SERVO)/EcSlaveIpos2401MxCat/*.cpp)
