INCLUDES += -I$(DIR_TASK_ETHERCAT_SLAVE_SERVO)/EcTaskEthercatSlaveServoBase
INCLUDES += -I$(DIR_TASK_ETHERCAT_SLAVE_SERVO)/EcTaskEthercatSlaveServoFactory
INCLUDES += -I$(DIR_TASK_ETHERCAT_SLAVE_SERVO)/EcCia402
INCLUDES += -I$(DIR_TASK_ETHERCAT_SLAVE_SERVO)/EcSlavePitchDrive
INCLUDES += -I$(DIR_TASK_ETHERCAT_SLAVE_SERVO)/EcSlaveDenNetE
INCLUDES += -I$(DIR_TASK_ETHERCAT_SLAVE_SERVO)/EcSlaveDenXcrE
INCLUDES += -I$(DIR_TASK_ETHERCAT_SLAVE_SERVO)/EcSlaveElmoDrive
INCLUDES += -I$(DIR_TASK_ETHERCAT_SLAVE_SERVO)/EcSlaveIpos2401MxCat
